name: my-first-actions

on: [push]

job:
  check-node-version:
    run-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - users: actions/setup-node@v3
        with:
          node-version: 16
      - run: npm ci
      - run: npm test
